import {ConverterDefinition} from '@app/types/files';

export const converters: ConverterDefinition[] = [
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    category: 'images',
    inputExtensions: ['png', 'jpg', 'jpeg', 'heic'],
    outputFormat: 'pdf',
    description: 'Combine PNG, JPG, JPEG, or HEIC files into a PDF.',
    supportsBatch: true,
  },
  {
    id: 'images-to-webp',
    name: 'Images to WebP',
    category: 'images',
    inputExtensions: ['png', 'jpg', 'jpeg', 'heic'],
    outputFormat: 'webp',
    description: 'Compress supported images into WebP.',
    supportsBatch: true,
    requiresNativeModule: 'webpConverter',
  },
  {
    id: 'image-to-jpg',
    name: 'Image to JPG',
    category: 'images',
    inputExtensions: ['png', 'heic'],
    outputFormat: 'jpg',
    description: 'Convert image formats into JPG.',
    supportsBatch: true,
  },
  {
    id: 'image-to-png',
    name: 'Image to PNG',
    category: 'images',
    inputExtensions: ['jpg', 'jpeg', 'heic'],
    outputFormat: 'png',
    description: 'Convert image formats into PNG.',
    supportsBatch: true,
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to Images',
    category: 'documents',
    inputExtensions: ['pdf'],
    outputFormat: 'png',
    description: 'Export every PDF page as an image.',
    supportsBatch: true,
    requiresNativeModule: 'pdfToImage',
  },
  {
    id: 'merge-pdfs',
    name: 'Merge PDFs',
    category: 'documents',
    inputExtensions: ['pdf'],
    outputFormat: 'pdf',
    description: 'Merge multiple PDFs into one output file.',
    supportsBatch: true,
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    category: 'documents',
    inputExtensions: ['docx'],
    outputFormat: 'pdf',
    description: 'Convert DOCX Word documents into PDF.',
    supportsBatch: true,
  },
  {
    id: 'pdf-to-docx-server',
    name: 'PDF to DOCX',
    category: 'documents',
    inputExtensions: ['pdf'],
    outputFormat: 'docx',
    description: 'Send PDF to a server and return a DOCX Word file.',
    supportsBatch: true,
    requiresServer: true,
    previewUnavailable: true,
  },
  {
    id: 'docx-to-txt',
    name: 'DOCX to TXT',
    category: 'documents',
    inputExtensions: ['docx'],
    outputFormat: 'txt',
    description: 'Extract plain text from DOCX.',
    supportsBatch: true,
  },
  {
    id: 'txt-to-pdf',
    name: 'TXT to PDF',
    category: 'documents',
    inputExtensions: ['txt'],
    outputFormat: 'pdf',
    description: 'Render text files into PDF.',
    supportsBatch: true,
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    category: 'documents',
    inputExtensions: ['html', 'htm'],
    outputFormat: 'pdf',
    description: 'Render HTML documents into PDF.',
    supportsBatch: true,
  },
  {
    id: 'md-to-pdf',
    name: 'Markdown to PDF',
    category: 'documents',
    inputExtensions: ['md', 'markdown'],
    outputFormat: 'pdf',
    description: 'Convert Markdown into PDF through HTML.',
    supportsBatch: true,
  },
  {
    id: 'excel-to-csv',
    name: 'Excel to CSV',
    category: 'sheets',
    inputExtensions: ['xls', 'xlsx'],
    outputFormat: 'csv',
    description: 'Export the first worksheet as CSV.',
    supportsBatch: true,
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    category: 'sheets',
    inputExtensions: ['xls', 'xlsx'],
    outputFormat: 'pdf',
    description: 'Render the first worksheet into a PDF table.',
    supportsBatch: true,
  },
  {
    id: 'excel-to-html',
    name: 'Excel to HTML',
    category: 'sheets',
    inputExtensions: ['xls', 'xlsx'],
    outputFormat: 'html',
    description: 'Export the first worksheet as HTML.',
    supportsBatch: true,
  },
  {
    id: 'csv-to-excel',
    name: 'CSV to Excel',
    category: 'sheets',
    inputExtensions: ['csv'],
    outputFormat: 'xlsx',
    description: 'Create an XLSX workbook from CSV rows.',
    supportsBatch: true,
  },
  {
    id: 'ppt-to-pdf-server',
    name: 'PowerPoint to PDF',
    category: 'slides',
    inputExtensions: ['ppt', 'pptx'],
    outputFormat: 'pdf',
    description: 'Send PPT or PPTX to a secure server for PDF conversion.',
    supportsBatch: true,
    requiresServer: true,
    previewUnavailable: true,
  },
  {
    id: 'ppt-to-text',
    name: 'Extract PowerPoint Text',
    category: 'slides',
    inputExtensions: ['ppt', 'pptx'],
    outputFormat: 'txt',
    description: 'Basic offline text extraction fallback for presentations.',
    supportsBatch: true,
    previewUnavailable: true,
  },
];

export function getConvertersByCategory(category: ConverterDefinition['category']) {
  return converters.filter(converter => converter.category === category);
}

export function getConverterById(id: string) {
  return converters.find(converter => converter.id === id);
}
